
export const TEXTS = {
  APP_TITLE: "Restaurante - App de Pedidos",
  APP_VERSION: "Menu | Versão 1.0",
  COMPANY_SOCIAL: "@Restaurante",

  // General
  CLOSE: "Fechar",
  CANCEL: "Cancelar",
  CONFIRM: "Confirmar",
  ADD: "Adicionar",
  REMOVE: "Remover",
  CLEAR: "Limpar",
  FINALIZE: "Finalizar",
  SAVE: "Salvar",
  YES: "Sim",
  NO: "Não",
  ERROR: "Erro",
  SUCCESS: "Sucesso",
  INFO: "Info",
  WARNING: "Atenção",
  OPTIONAL_BRACKETS: "(Opcional)",


  // Header
  HEADER_MAIN_TITLE: "CARDÁPIO",
  HEADER_SUB_TITLE: "Restaurante",

  // View Switcher
  VIEW_MENU: "Cardápio",
  VIEW_MANAGE_COMANDAS: "Gerenciar Comandas",

  // Order Summary
  ORDER_SUMMARY_TITLE_CURRENT: "COMANDA ATUAL",
  ORDER_SUMMARY_TITLE_ADDING_PREFIX: "ADICIONANDO À C. Nº",
  ORDER_SUMMARY_NO_ITEMS_CURRENT: "Nenhum item na comanda.",
  ORDER_SUMMARY_NO_ITEMS_ADDING: "Nenhum item selecionado para adição.",
  ORDER_SUMMARY_TOTAL_LABEL: "TOTAL",
  ORDER_SUMMARY_TOTAL_ADDING_SUFFIX: " DA ADIÇÃO",
  ORDER_SUMMARY_FINALIZE_BUTTON: "Finalizar Comanda",
  ORDER_SUMMARY_ADD_TO_COMANDA_BUTTON_PREFIX: "Adicionar à C. Nº",
  ORDER_SUMMARY_CLEAR_BUTTON: "Limpar Comanda",
  ORDER_SUMMARY_CANCEL_ADDITION_BUTTON: "Cancelar Adição",

  // MenuItemCard
  MENU_ITEM_ADD_BUTTON: "Adicionar",
  MENU_ITEM_ADD_TO_COMANDA_BUTTON_SUFFIX: " à Comanda", 

  // OrderItemCard
  ORDER_ITEM_CARD_EDIT_OBSERVATION_ARIA_LABEL_PREFIX: "Adicionar ou editar observação para ",
  ORDER_ITEM_CARD_OBSERVATION_LABEL: "Obs:",

  // ComandaDetail
  COMANDA_DETAIL_OBSERVATION_LABEL: "Observação:",

  // Modal
  MODAL_BUTTON_COPY_TEXT: "Copiar Texto",
  MODAL_FINALIZE_COMANDA_CONFIRM_PROMPT: "Confirmar e finalizar esta nova comanda?",
  MODAL_FINALIZE_COMANDA_YES_BUTTON: "Sim, Finalizar",
  MODAL_CUSTOMER_NAME_PROMPT: "Qual o nome para esta comanda?",
  MODAL_CUSTOMER_NAME_LABEL: "Nome do Cliente (Opcional)",
  MODAL_CUSTOMER_NAME_PLACEHOLDER: "Ex: João Silva",
  MODAL_SAVE_COMANDA_BUTTON: "Salvar Comanda",
  MODAL_FINALIZE_WITHOUT_NAME_BUTTON: "Finalizar sem Nome",
  MODAL_CLEAR_BEFORE_ADD_ITEMS_PROMPT: "Você tem itens na comanda atual. Deseja limpá-los antes de adicionar à outra comanda?",
  MODAL_CLEAR_BEFORE_ADD_ITEMS_CONFIRM_BUTTON: "Limpar e Continuar",
  MODAL_CLEAR_BEFORE_ADD_ITEMS_CANCEL_BUTTON: "Cancelar Ação",
  MODAL_REMOVE_ITEM_PROMPT_PREFIX: "Tem certeza que deseja remover \"",
  MODAL_REMOVE_ITEM_PROMPT_SUFFIX: "\" da comanda?",
  MODAL_CLEAR_ORDER_PROMPT: "Tem certeza que deseja limpar todos os itens da comanda atual?",
  MODAL_CLEAR_ORDER_ADDING_PROMPT: "Tem certeza que deseja limpar os itens selecionados para adição e cancelar?",
  MODAL_CLEAR_ORDER_CONFIRM_BUTTON: "Limpar Tudo",
  MODAL_CLEAR_ORDER_ADDING_CONFIRM_BUTTON: "Limpar e Cancelar",
  MODAL_EXPORT_PROMPT: "Copie o texto abaixo para exportar suas comandas:",
  MODAL_EXPORT_TEXTAREA_LABEL: "Dados das Comandas Exportadas",
  MODAL_IMPORT_PROMPT: "Cole o texto das comandas exportadas abaixo:",
  MODAL_IMPORT_TEXTAREA_LABEL: "Dados das Comandas para Importar",
  MODAL_IMPORT_TEXTAREA_PLACEHOLDER: "Cole o texto exportado aqui...",
  MODAL_IMPORT_BUTTON: "Importar",
  MODAL_DELETE_COMANDA_PROMPT_PREFIX: "Tem certeza que deseja excluir permanentemente a Comanda ",
  MODAL_DELETE_COMANDA_PROMPT_CLIENT_PREFIX: " do cliente ",
  MODAL_DELETE_COMANDA_PROMPT_SUFFIX: "? Esta ação não pode ser desfeita.",
  MODAL_DELETE_COMANDA_CONFIRM_BUTTON: "Sim, Excluir",
   MODAL_OBSERVATION_TITLE_PREFIX: "Observação para ",
  MODAL_OBSERVATION_TEXTAREA_LABEL: "Observação (opcional):",
  MODAL_OBSERVATION_TEXTAREA_PLACEHOLDER: "Ex: Sem cebola, mais queijo, etc.",
  MODAL_OBSERVATION_CONFIRM_BUTTON: "Salvar Observação",
  MODAL_OBSERVATION_REMOVE_BUTTON: "Remover Observação",

  // AddonsSelectionModal
  ADDONS_MODAL_TITLE_PREFIX: "Adicionais para ",
  ADDONS_MODAL_SELECT_PROMPT: "Selecione a quantidade de cada adicional:",
  ADDONS_MODAL_SKIP_BUTTON: "Pular Adicionais",
  ADDONS_MODAL_CONFIRM_BUTTON: "Confirmar Adicionais",

  // ManageComandasView & ComandaDetail & ComandaListItem
  MANAGE_COMANDAS_TITLE: "Comandas Finalizadas",
  MANAGE_COMANDAS_NO_COMANDAS: "Nenhuma comanda finalizada ainda.",
  MANAGE_COMANDAS_EXPORT_BUTTON: "Exportar",
  MANAGE_COMANDAS_IMPORT_BUTTON: "Importar",
  COMANDA_DETAIL_TITLE: "Detalhes da Comanda",
  COMANDA_DETAIL_BACK_BUTTON_TEXT: "Voltar à Lista",
  COMANDA_DETAIL_BACK_BUTTON_ARIA_LABEL: "Voltar à lista de comandas",
  COMANDA_DETAIL_LABEL_REFERENCE: "Referência",
  COMANDA_DETAIL_LABEL_CUSTOMER: "Cliente",
  COMANDA_DETAIL_LABEL_CREATED_AT: "Criada em",
  COMANDA_DETAIL_LABEL_UPDATED_AT: "Última Atualização",
  COMANDA_DETAIL_LABEL_STATUS: "Status Atual",
  COMANDA_DETAIL_LABEL_TOTAL: "Total Geral",
  COMANDA_DETAIL_UPDATE_STATUS_LABEL: "Atualizar Status:",
  COMANDA_DETAIL_UPDATE_STATUS_ARIA_LABEL: "Selecionar novo status da comanda",
  COMANDA_DETAIL_ADDITIONAL_ACTIONS_LABEL: "Ações Adicionais:",
  COMANDA_DETAIL_ADD_MORE_ITEMS_BUTTON: "Adicionar Mais Itens",
  COMANDA_DETAIL_ITEMS_TITLE: "Itens da Comanda:",
  COMANDA_DETAIL_NO_ITEMS: "Nenhum item nesta comanda.",
  COMANDA_DETAIL_SESSION_INITIAL_ITEMS: "Itens Iniciais Adicionados em:",
  COMANDA_DETAIL_SESSION_ADDITIONAL_ITEMS: "Itens Adicionais Adicionados em:",
  COMANDA_DETAIL_DANGER_ZONE_TITLE: "Zona de Perigo",
  COMANDA_DETAIL_DELETE_BUTTON_TEXT: "Excluir Comanda Permanentemente",
  COMANDA_DETAIL_DELETE_BUTTON_ARIA_LABEL_PREFIX: "Excluir permanentemente a comanda ",
  COMANDA_LIST_ITEM_VIEW_DETAILS_BUTTON: "Ver Detalhes",
  COMANDA_LIST_ITEM_COMANDA_NUMBER_PREFIX: "Comanda Nº ",
  COMANDA_LIST_ITEM_ID_PREFIX: "ID: ",
  COMANDA_LIST_ITEM_CUSTOMER_PREFIX: "Cliente: ",

  // Toasts / Notifications
  TOAST_ADDING_ITEM_SELECT_ADDONS_PREFIX: "\"",
  TOAST_ADDING_ITEM_SELECT_ADDONS_SUFFIX: "\" selecionado. Escolha os adicionais.",
  TOAST_ADDING_ITEM_TO_EXISTING_SELECT_ADDONS_PREFIX: "Adicionando \"",
  TOAST_ADDING_ITEM_TO_EXISTING_SELECT_ADDONS_SUFFIX: "\". Selecione os adicionais.",
  TOAST_ITEM_QUANTITY_INCREASED_PREFIX: "\"",
  TOAST_ITEM_QUANTITY_INCREASED_SUFFIX: "\" quantidade aumentada!",
  TOAST_ADDITION_CANCELED: "Adição de itens cancelada.",
  TOAST_FINALIZE_ADD_ITEMS_FIRST: "Adicione itens antes de continuar.",
  TOAST_COMANDA_FINALIZED_WITHOUT_NAME: "Comanda finalizada sem nome.",
  TOAST_SWITCH_VIEW_FINISH_ADDITION_FIRST: "Finalize ou cancele a adição de itens atual.",
  TOAST_ENTERING_ADD_MODE_PREFIX: "Modo de adição para Comanda Nº ",
  TOAST_ENTERING_ADD_MODE_SUFFIX: ". Adicione itens.",
  TOAST_TEXT_COPIED_SUCCESS: "Texto copiado para a área de transferência!",
  TOAST_TEXT_COPIED_FAIL: "Falha ao copiar texto. Tente manualmente.",
  TOAST_NO_TEXT_TO_COPY: "Nenhum texto para copiar.",
  TOAST_NO_COMANDAS_TO_EXPORT: "Nenhuma comanda para exportar.",
  TOAST_NO_IMPORT_TEXT_PROVIDED: "Nenhum texto fornecido para importação.",
  TOAST_IMPORT_WITH_ALERTS_PREFIX: "Importação concluída com ",
  TOAST_IMPORT_WITH_ALERTS_SUFFIX: " alerta(s). Verifique o console.",
  TOAST_IMPORT_SUCCESS_COUNT_PREFIX: "",
  TOAST_IMPORT_SUCCESS_COUNT_SUFFIX: " comanda(s) importada(s). ",
  TOAST_IMPORT_DUPLICATE_COUNT_PREFIX: "",
  TOAST_IMPORT_DUPLICATE_COUNT_SUFFIX: " duplicada(s) ignorada(s). ",
  TOAST_IMPORT_NO_NEW_COMANDAS: "Nenhuma comanda nova importada (possivelmente todas já existiam).",
  TOAST_IMPORT_NO_VALID_COMANDAS_FOUND: "Nenhuma comanda válida encontrada no texto para importação.",
  TOAST_IMPORT_CRITICAL_ERROR: "Ocorreu um erro crítico ao importar. Verifique o formato do texto.",
  TOAST_COMANDA_DELETED_PREFIX: "Comanda ",
  TOAST_COMANDA_DELETED_SUFFIX: " excluída.",
  TOAST_ERROR_LOADING_COMANDAS_HISTORY: "Erro ao carregar histórico de comandas.",
  TOAST_ERROR_LOADING_CURRENT_SAVED_ORDER: "Erro ao carregar comanda atual salva.",
  TOAST_NEW_COMANDA_FINALIZED_NUMBER_PREFIX: "Comanda Nº ",
  TOAST_NEW_COMANDA_FINALIZED_CUSTOMER_PREFIX: " de ",
  TOAST_NEW_COMANDA_FINALIZED_SUFFIX: " finalizada!",
  TOAST_COMANDA_STATUS_UPDATED_NUMBER_PREFIX: "Status da Comanda Nº ",
  TOAST_COMANDA_STATUS_UPDATED_UNKNOWN_ID: "desconhecida",
  TOAST_COMANDA_STATUS_UPDATED_STATUS_SUFFIX: " atualizado para ",
  TOAST_ITEMS_ADDED_TO_COMANDA_NUMBER_PREFIX: "Itens adicionados à Comanda Nº ",
  TOAST_ITEMS_ADDED_TO_COMANDA_UNKNOWN_ID: "desconhecida",
  TOAST_ITEMS_ADDED_TO_COMANDA_SUFFIX: ".",
  TOAST_NO_ITEMS_TO_ADD: "Nenhum item para adicionar.",
  TOAST_ITEM_ADDED_TO_CURRENT_ORDER_NAME_PREFIX: "\"",
  TOAST_ITEM_ADDED_TO_CURRENT_ORDER_SUFFIX: "\" adicionado à comanda atual!",
  TOAST_ITEM_ADDED_TO_EXISTING_COMANDA_NAME_PREFIX: "\"",
  TOAST_ITEM_ADDED_TO_EXISTING_COMANDA_NUMBER_MIDFIX: "\" adicionado para C. Nº ",
  TOAST_ITEM_ADDED_TO_EXISTING_COMANDA_SUFFIX: ".",
  TOAST_ITEM_REMOVED_NAME_PREFIX: "\"",
  TOAST_ITEM_REMOVED_SUFFIX: "\" removido.",
  TOAST_CURRENT_ORDER_ALREADY_EMPTY: "A comanda atual já está vazia.",
  TOAST_ADDITION_CANCELED_ITEMS_CLEARED: "Adição cancelada e itens limpos.",
  TOAST_CURRENT_ORDER_CLEARED: "Comanda atual limpa!",
  TOAST_ITEM_OBSERVATION_UPDATED_PREFIX: "Observação para \"",
  TOAST_ITEM_OBSERVATION_UPDATED_SUFFIX: "\" atualizada.",
  TOAST_ITEM_OBSERVATION_REMOVED_PREFIX: "Observação para \"",
  TOAST_ITEM_OBSERVATION_REMOVED_SUFFIX: "\" removida.",
};
